version: '2'
services:
  web:
    build: .
    command: echo 'ready'
    volumes:
      - .:/home/app/palette1
#      - /usr/app/node_modules
    ports:
      - "3000:3000"
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgres://todoapp@postgres/todos
#  postgres:
#    image: postgres:9.6.2-alpine
#    environment:
#      POSTGRES_USER: todoapp
#      POSTGRES_DB: todos

